import * as fs from 'fs/promises';
import * as path from 'path';
import { Application } from '@prisma/client';
import { appDirFor, sourcesDirFor, logsDirFor, currentDirFor } from '../lib/appPaths';
import { detectProject } from '../lib/projectDetect';
import { appUnit, OS_ISOLATION_ENABLED } from './orgProvisionService';

/**
 * Application runtime.
 *
 * Each app runs as a systemd unit under its organization's OS user, inside
 * that organization's cgroup slice, so a runaway tenant is capped on CPU and
 * memory and cannot read another tenant's files.
 *
 * PHP and STATIC apps get no unit: PHP is served by the org's PHP-FPM pool
 * (created by cb-provision-org) and static sites are served from R2/Caddy.
 */

const DEFAULT_PORTS: Record<string, number> = {
  NODEJS: 3000,
  PYTHON: 8000,
  GO: 8080,
  RUST: 8080,
  JAVA: 8080,
};

const DEFAULT_START_COMMANDS: Record<string, string> = {
  NODEJS: 'npm start',
  PYTHON: 'python app.py',
  GO: './main',
  RUST: './app',
  JAVA: 'java -jar app.jar',
};

/** STATIC and PHP are served by Caddy / PHP-FPM, not by a unit of their own. */
export function needsUnit(type: string): boolean {
  return type !== 'STATIC' && type !== 'PHP';
}

export function defaultPort(type: string): number {
  return DEFAULT_PORTS[type] ?? 3000;
}

/** Single-quote a value for safe interpolation into a bash export. */
function shellQuote(value: string): string {
  return `'${String(value).replace(/'/g, `'\''`)}'`;
}

/**
 * Write the script the unit executes. Environment variables are exported here
 * rather than through an EnvironmentFile so that values containing spaces,
 * quotes or newlines survive intact.
 */
export async function writeRunScript(application: Application, appDir: string): Promise<string> {
  const runPath = path.join(appDir, 'run.sh');
  const port = application.port || defaultPort(application.type);

  // Run from the built release when there is one; apps deployed before the
  // releases layout existed still run from sources/.
  const currentDir = currentDirFor(appDir);
  const runDir = (await fs.stat(currentDir).then((s) => s.isDirectory()).catch(() => false))
    ? currentDir
    : sourcesDirFor(appDir);

  let startCommand: string | null = application.startCommand;
  if (!startCommand && application.type === 'NODEJS') {
    startCommand = (await detectProject(runDir)).startCommand;
  }
  startCommand = startCommand || DEFAULT_START_COMMANDS[application.type] || 'npm start';

  const envVars = (application.envVars || {}) as Record<string, string>;
  const exports = Object.entries(envVars)
    .filter(([key]) => /^[A-Za-z_][A-Za-z0-9_]*$/.test(key))
    .map(([key, value]) => `export ${key}=${shellQuote(value)}`);

  const script = [
    '#!/bin/bash',
    '# Generated by CommitBase. Edits are overwritten on the next deploy.',
    'set -euo pipefail',
    '',
    'export NODE_ENV=production',
    `export PORT=${port}`,
    `export HOST=127.0.0.1`,
    ...exports,
    '',
    `cd ${shellQuote(runDir)}`,
    `exec ${startCommand}`,
    '',
  ].join('\n');

  await fs.mkdir(logsDirFor(appDir), { recursive: true });
  await fs.writeFile(runPath, script, { mode: 0o755 });
  return runPath;
}

export interface AppWithOrg extends Application {
  organization?: { slug: string } | null;
}

function slugOf(application: AppWithOrg): string {
  const slug = application.organization?.slug;
  if (!slug) {
    throw new Error(
      `Application ${application.id} has no organization — assign it one before using the native runtime`
    );
  }
  return slug;
}

export async function startApplication(application: AppWithOrg): Promise<boolean> {
  if (!OS_ISOLATION_ENABLED) throw new Error('ORG_OS_ISOLATION is not enabled');
  if (!needsUnit(application.type)) return true;

  const slug = slugOf(application);
  const appDir = appDirFor(application.id, slug);

  await writeRunScript(application, appDir);
  await appUnit('install', slug, application.id); // also hands the tree to the tenant user
  await appUnit('start', slug, application.id);

  return (await getStatus(application)) === 'RUNNING';
}

export async function stopApplication(application: AppWithOrg): Promise<void> {
  if (!needsUnit(application.type)) return;
  await appUnit('stop', slugOf(application), application.id);
}

export async function restartApplication(application: AppWithOrg): Promise<void> {
  if (!needsUnit(application.type)) return;
  await appUnit('restart', slugOf(application), application.id);
}

export async function removeApplication(application: AppWithOrg): Promise<void> {
  if (!needsUnit(application.type)) return;
  await appUnit('remove', slugOf(application), application.id);
}

export async function getStatus(application: AppWithOrg): Promise<'RUNNING' | 'STOPPED'> {
  if (!needsUnit(application.type)) return 'RUNNING';
  try {
    const out = await appUnit('status', slugOf(application), application.id);
    return out.trim() === 'active' ? 'RUNNING' : 'STOPPED';
  } catch {
    return 'STOPPED';
  }
}
