import * as path from 'path';
import { Application } from '@prisma/client';
import { sourcesDirFor, logsDirFor, currentDirFor } from '../lib/appPaths';
import { appFsFor, remoteCommand, type AppFs } from '../lib/appFs';
import { exec, type SshTarget } from '../lib/runner';
import { detectProject, nvmPreamble } from '../lib/projectDetect';
import { readEnv } from '../lib/appEnv';
import { appUnit } from './orgProvisionService';

/**
 * Application runtime.
 *
 * Each app runs as a systemd unit under its organization's OS user, inside
 * that organization's cgroup slice, so a runaway tenant is capped on CPU and
 * memory and cannot read another tenant's files.
 *
 * PHP and STATIC apps get no unit: PHP is served by the org's PHP-FPM pool
 * (created by cb-provision-org) and static sites are served from R2/Caddy.
 */

const DEFAULT_PORTS: Record<string, number> = {
  NODEJS: 3000,
  PYTHON: 8000,
  GO: 8080,
  RUST: 8080,
  JAVA: 8080,
};

const DEFAULT_START_COMMANDS: Record<string, string> = {
  NODEJS: 'npm start',
  PYTHON: 'python app.py',
  GO: './main',
  RUST: './app',
  JAVA: 'java -jar app.jar',
};

/** STATIC and PHP are served by Caddy / PHP-FPM, not by a unit of their own. */
export function needsUnit(type: string): boolean {
  return type !== 'STATIC' && type !== 'PHP';
}

export function defaultPort(type: string): number {
  return DEFAULT_PORTS[type] ?? 3000;
}

/** Single-quote a value for safe interpolation into a bash export. */
function shellQuote(value: string): string {
  return `'${String(value).replace(/'/g, `'\''`)}'`;
}

/**
 * Write the script the unit executes. Environment variables are exported here
 * rather than through an EnvironmentFile so that values containing spaces,
 * quotes or newlines survive intact.
 */
export async function writeRunScript(application: Application, afs: AppFs): Promise<string> {
  const { appDir } = afs;
  const runPath = path.posix.join(appDir, 'run.sh');
  const port = application.port || defaultPort(application.type);

  // Run from the built release when there is one; apps deployed before the
  // releases layout existed still run from sources/.
  const currentDir = currentDirFor(appDir);
  const runDir = (await afs.isDirectory(currentDir))
    ? currentDir
    : sourcesDirFor(appDir);

  let startCommand: string | null = application.startCommand;
  let nodeVersion: string | null = null;
  if (application.type === 'NODEJS') {
    const detected = await detectProject(runDir, afs.readText);
    nodeVersion = detected.nodeVersion;
    if (!startCommand) startCommand = detected.startCommand;
  }
  startCommand = startCommand || DEFAULT_START_COMMANDS[application.type] || 'npm start';

  const envVars = readEnv(application.envVars);
  const exports = Object.entries(envVars)
    // PORT and the bind address are the platform's: the proxy dials exactly that
    // port on loopback, so an app env copied from local (PORT=3000) must not move it
    .filter(([key]) => /^[A-Za-z_][A-Za-z0-9_]*$/.test(key) && !['PORT', 'HOST', 'HOSTNAME'].includes(key))
    .map(([key, value]) => `export ${key}=${shellQuote(value)}`);

  const script = [
    '#!/bin/bash',
    '# Generated by Larika. Edits are overwritten on the next deploy.',
    'set -euo pipefail',
    '',
    ...(application.type === 'NODEJS' ? nvmPreamble(nodeVersion, false) : []),
    'export NODE_ENV=production',
    `export PORT=${port}`,
    `export HOST=127.0.0.1`,
    // Next's standalone server.js binds to HOSTNAME, not HOST
    `export HOSTNAME=127.0.0.1`,
    ...exports,
    '',
    `cd ${shellQuote(runDir)}`,
    `exec ${startCommand}`,
    '',
  ].join('\n');

  await afs.mkdir(logsDirFor(appDir));
  await afs.writeFile(runPath, script, { mode: 0o755 });
  return runPath;
}

export interface AppWithOrg extends Application {
  organization?: { slug: string } | null;
}

function slugOf(application: AppWithOrg): string {
  const slug = application.organization?.slug;
  if (!slug) {
    throw new Error(
      `Application ${application.id} has no organization — assign it one before using the native runtime`
    );
  }
  return slug;
}

export async function startApplication(application: AppWithOrg): Promise<boolean> {
  if (!needsUnit(application.type)) return true;

  const slug = slugOf(application);

  await writeRunScript(application, await appFsFor(application.id));
  await appUnit('install', slug, application.id); // also hands the tree to the tenant user
  // restart, not start: `start` is a no-op on a running unit, so a redeploy kept
  // the old process serving from its old release — until cleanup deleted that tree
  await appUnit('restart', slug, application.id);

  return (await getStatus(application)) === 'RUNNING';
}

export async function stopApplication(application: AppWithOrg): Promise<void> {
  if (!needsUnit(application.type)) return;
  await appUnit('stop', slugOf(application), application.id);
}

export async function restartApplication(application: AppWithOrg): Promise<void> {
  if (!needsUnit(application.type)) return;
  const slug = slugOf(application);
  // Env vars live in run.sh — rewrite it so an edit takes effect on restart.
  await writeRunScript(application, await appFsFor(application.id));
  await appUnit('restart', slug, application.id);
}

export async function removeApplication(application: AppWithOrg): Promise<void> {
  if (!needsUnit(application.type)) return;
  await appUnit('remove', slugOf(application), application.id);
}

/**
 * Follow a unit app's log files on its node: the last `lines` lines, then each
 * new one, until `signal` aborts. The unit appends stdout to out.log and stderr
 * to error.log; `combined` tails both, tail marking each switch with
 * `==> file <==`. -F reopens a file that logrotate truncates or that does not
 * exist yet (an app never started).
 */
export function followLogs(
  node: SshTarget,
  logsDir: string,
  type: 'combined' | 'out' | 'error',
  lines: number,
  onOutput: (text: string) => void,
  signal: AbortSignal
): Promise<unknown> {
  const files = type === 'out' ? ['out.log'] : type === 'error' ? ['error.log'] : ['out.log', 'error.log'];
  const { argv } = remoteCommand(['tail', '-n', String(lines), '-F', ...files], { cwd: logsDir });
  // backstop only: the route aborts well before this
  return exec(node, argv, { onOutput, signal, maxBuffer: 0, timeout: 2 * 60 * 60_000 });
}

export async function getStatus(application: AppWithOrg): Promise<'RUNNING' | 'STOPPED'> {
  if (!needsUnit(application.type)) return 'RUNNING';
  try {
    const out = await appUnit('status', slugOf(application), application.id);
    return out.trim() === 'active' ? 'RUNNING' : 'STOPPED';
  } catch {
    return 'STOPPED';
  }
}
